# DO NOT REMOVE THE TAGS (!Config, !FeedConfig, etc.)
#
# The following setting should silence unknown tag errors in VS Code:
#
#    "yaml.customTags": [
#         "!Config mapping",
#         "!FeedConfig mapping"
#    ]
!Config
feed: !FeedConfig
  # Base part of the feeds' canonical URLs, i.e., the feeds are to be served as
  # <base_url>/aggregate.xml, <base_url>/<package>.xml, etc. Trailing slash is
  # optional.
  #
  # This parameter is REQUIRED.
  base_url: https://release-feeds.zhimingwang.org/

  # Author of the feeds. Defaults to "release-feeds".
  #author: release-feeds

  # Title of the aggregate feed. Defaults to "Aggregate software releases". Note
  # that the title of the release feed for each individual package is always
  # "<package> releases" and not affected by this setting.
  #aggregate_title: Aggregate software releases

# A list of packages to monitor.
#
# Each entry bootstrapped from Debian should be the name of a Debian source
# package available at https://sources.debian.org/ for the sid (unstable)
# distribution. Note that not every Debian source package has a debian/watch
# file.
#
# You can find the source package corresponding to a binary package next to
# "Download Source Package" on the binary package page
# https://packages.debian.org/sid/<package>.
#
# Alternatively, to monitor packages not in Debian, or packages without existing
# debian/watch, you can add your own watch file to watch_overrides/<package>.
packages:
  - ffmpeg
  - golang-defaults
  - python3-defaults
  - rustc
  - zsh
