name: update
on:
  push:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends devscripts
          python3 -m pip install -U pip
          python3 -m pip install -r src/requirements.txt
      - name: Check for new versions and update feeds
        run: |
          set -x
          addtional_options=()
          git log --format=%B -n1 | grep -q '\[regenerate\]' && additional_options+=(--regenerate)
          # The following command sets the LOGFILE env var.
          python3 src/update.py -j8 "${additional_options[@]}"
      - name: Commit and push changes
        if: ${{ always() }}
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add docs
          git diff --cached --quiet || git commit -m 'Update feeds (from GitHub Actions)'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove log file on success
        if: ${{ success() }}
        run: |
          [[ -n $LOGFILE ]] && rm -f $LOGFILE
      - name: Checkout logs branch
        if: ${{ always() }}
        uses: actions/checkout@v2
        with:
          ref: logs
          clean: false
      - name: Trim log files
        if: ${{ always() }}
        run: |
          git checkout $GITHUB_SHA -- src/logfiles.py && git reset src/logfiles.py
          python3 src/logfiles.py
      - name: Commit and push log files
        if: ${{ always() }}
        run: |
          git add '*.log' || true
          git diff --cached --quiet || git commit -m 'Update logs (from GitHub Actions)'
          git push
